version: '2.4'

services:
  mongo:
    image: {{image}}
    container_name: {{container_name}}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db:delegated

volumes:
  mongo-data:
    external:
      name: {{projectname}}-mongo-data
