version: '2.4'

services:
  mongo:
    image: {{image}}
    container_name: {{container_name}}
    ports:
      - 27017:27017
    user: ${CURRENT_UID}
    volumes:
{{mapped-volumes}}
      - ../.volumes/mongo-data:/data/db:delegated
{{/mapped-volumes}}
{{named-volumes}}
      - mongo-data:/data/db:delegated

volumes:
  mongo-data:
    external:
      name: {{volumesPrefix}}-mongo-data
{{/named-volumes}}
